// Command chainpulse is the unified CLI for ChainPulse.
//
// Subcommands:
//
//	run         Start the service (monolithic mode)
//	playground  Start the zero-dependency playground
//	status      Query service health
//
// Use "chainpulse <subcommand> -h" for subcommand help.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"text/template"
	"time"
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	switch os.Args[1] {
	case "run":
		runMonolithic(ctx)
	case "playground":
		runPlayground(ctx)
	case "status":
		runStatus(ctx)
	case "gen-abi":
		runGenABI(ctx)
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand: %s\n", os.Args[1])
		printUsage()
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Print(`ChainPulse — Web3 Event Indexer

Usage:
  chainpulse run          Start monolithic mode (requires env config)
  chainpulse playground   Start zero-dependency in-memory playground
  chainpulse status       Query a running instance health
  chainpulse gen-abi      Generate Go structs from Solidity ABI JSON

Examples:
  chainpulse playground
  chainpulse gen-abi -abi ./abi.json -out ./events_gen.go
  curl http://localhost:9099/stats
`)
}

func runMonolithic(ctx context.Context) {
	cmd := exec.CommandContext(ctx, os.Args[0], append([]string{"-cmd"}, os.Args[2:]...)...)
	// In a real build this would invoke the monolithic binary directly.
	// For now, print the command that matches the repo layout.
	fmt.Println("Starting monolithic mode...")
	fmt.Println("Use: go run ./cmd/monolithic/chainpulse/")
	_ = cmd
}

func runPlayground(ctx context.Context) {
	cmd := exec.Command("go", "run", "./cmd/playground/")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "playground failed: %v\n", err)
		os.Exit(1)
	}
}

func runGenABI(ctx context.Context) {
	abiPath := ""
	outFile := ""
	pkg := "contracts"

	args := os.Args[2:]
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "-abi":
			if i+1 < len(args) {
				abiPath = args[i+1]
				i++
			}
		case "-out":
			if i+1 < len(args) {
				outFile = args[i+1]
				i++
			}
		case "-pkg":
			if i+1 < len(args) {
				pkg = args[i+1]
				i++
			}
		}
	}

	if abiPath == "" || outFile == "" {
		fmt.Fprintf(os.Stderr, "Usage: chainpulse gen-abi -abi <path> -out <path> [-pkg <name>]\n")
		os.Exit(1)
	}

	if err := generateABIFromFile(abiPath, outFile, pkg); err != nil {
		fmt.Fprintf(os.Stderr, "gen-abi: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated Go event structs → %s\n", outFile)
}

type abiJSON struct {
	ABI []abiEntry `json:"abi"`
}

type abiEntry struct {
	Type   string     `json:"type"`
	Name   string     `json:"name"`
	Inputs []abiParam `json:"inputs"`
}

type abiParam struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Indexed bool   `json:"indexed"`
}

type genEvent struct {
	Name   string
	Fields []genField
}

type genField struct {
	Name    string
	GoType  string
	JSONTag string
}

func generateABIFromFile(abiPath, outFile, pkg string) error {
	data, err := os.ReadFile(abiPath)
	if err != nil {
		return fmt.Errorf("read ABI: %w", err)
	}

	var abi abiJSON
	if err := json.Unmarshal(data, &abi); err != nil {
		return fmt.Errorf("parse ABI JSON: %w", err)
	}

	var events []genEvent
	for _, entry := range abi.ABI {
		if entry.Type != "event" {
			continue
		}
		ev := genEvent{Name: toPascalCase(entry.Name)}
		for _, input := range entry.Inputs {
			fd := genField{
				Name:    toPascalCase(input.Name),
				GoType:  solToGo(input.Type),
				JSONTag: input.Name,
			}
			ev.Fields = append(ev.Fields, fd)
		}
		events = append(events, ev)
	}

	if len(events) == 0 {
		return fmt.Errorf("no events found in ABI")
	}

	return renderGoFile(outFile, pkg, events)
}

func solToGo(t string) string {
	switch {
	case t == "address":
		return "common.Address"
	case t == "bytes32":
		return "[32]byte"
	case t == "string":
		return "string"
	case t == "bool":
		return "bool"
	case strings.HasPrefix(t, "uint256"), strings.HasPrefix(t, "int256"),
		strings.HasPrefix(t, "uint128"), strings.HasPrefix(t, "int128"):
		return "*big.Int"
	case strings.HasPrefix(t, "uint"), strings.HasPrefix(t, "int"):
		return t
	case strings.HasPrefix(t, "bytes"):
		return "[]byte"
	default:
		return "interface{}"
	}
}

func toPascalCase(name string) string {
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	result := strings.Join(parts, "")
	if len(result) > 0 && result[0] >= 'a' && result[0] <= 'z' {
		result = strings.ToUpper(result[:1]) + result[1:]
	}
	return result
}

func renderGoFile(outFile, pkg string, events []genEvent) error {
	tmplSrc := "// Code generated by chainpulse gen-abi; DO NOT EDIT.\n\n" +
		"package {{.Pkg}}\n\n" +
		"import (\n" +
		`	"math/big"` + "\n\n" +
		`	"github.com/ethereum/go-ethereum/common"` + "\n" +
		")\n\n" +
		"{{range .Events}}" +
		"// {{.Name}} represents the Solidity event.\n" +
		"type {{.Name}} struct {\n" +
		"{{- range .Fields}}" +
		"\t{{.Name}} {{.GoType}} `json:\"{{.JSONTag}}\"`\n" +
		"{{- end}}" +
		"}\n\n" +
		"{{end}}"

	t, err := template.New("abi").Parse(tmplSrc)
	if err != nil {
		return err
	}

	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	defer f.Close()

	type tmplData struct {
		Pkg    string
		Events []genEvent
	}
	return t.Execute(f, tmplData{Pkg: pkg, Events: events})
}

func runStatus(ctx context.Context) {
	port := "9099"
	if p := os.Getenv("PLAYGROUND_PORT"); p != "" {
		port = p
	}

	client := &http.Client{Timeout: 3 * time.Second}
	resp, err := client.Get(fmt.Sprintf("http://localhost:%s/stats", port))
	if err != nil {
		if errors.Is(err, context.DeadlineExceeded) || errors.Is(err, os.ErrDeadlineExceeded) {
			fmt.Fprintf(os.Stderr, "no instance responding on :%s\n", port)
		} else {
			fmt.Fprintf(os.Stderr, "status check failed: %v\n", err)
		}
		os.Exit(1)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	var pretty map[string]any
	if err := json.Unmarshal(body, &pretty); err == nil {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		_ = enc.Encode(pretty)
	} else {
		fmt.Println(string(body))
	}
}
