linters-settings:
  govet:
    disable:
      - fieldalignment
      - unusedwrite
linters:
  disable-all: true
  enable:
    - govet
issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same: 0
