linters-settings:
  errcheck:
    check-type-assertions: false
  govet:
    check-shadowing: false
linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same: 0
