package codegen

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"text/template"
)

type abiJSON struct {
	ABI []abiEntry `json:"abi"`
}

type abiEntry struct {
	Type   string     `json:"type"`
	Name   string     `json:"name"`
	Inputs []abiParam `json:"inputs"`
}

type abiParam struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Indexed bool   `json:"indexed"`
}

type GenEvent struct {
	Name   string
	Fields []GenField
}

type GenField struct {
	Name    string
	GoType  string
	JSONTag string
}

func GenerateABIFromFile(abiPath, outFile, pkg string) error {
	data, err := os.ReadFile(abiPath)
	if err != nil {
		return fmt.Errorf("read ABI: %w", err)
	}

	var abi abiJSON
	if err := json.Unmarshal(data, &abi); err != nil {
		return fmt.Errorf("parse ABI JSON: %w", err)
	}

	var events []GenEvent
	for _, entry := range abi.ABI {
		if entry.Type != "event" {
			continue
		}
		ev := GenEvent{Name: toPascalCase(entry.Name)}
		for _, input := range entry.Inputs {
			fd := GenField{
				Name:    toPascalCase(input.Name),
				GoType:  solToGo(input.Type),
				JSONTag: input.Name,
			}
			ev.Fields = append(ev.Fields, fd)
		}
		events = append(events, ev)
	}

	if len(events) == 0 {
		return fmt.Errorf("no events found in ABI")
	}

	return renderGoFile(outFile, pkg, events)
}

func solToGo(t string) string {
	switch {
	case t == "address":
		return "common.Address"
	case t == "bytes32":
		return "[32]byte"
	case t == "string":
		return "string"
	case t == "bool":
		return "bool"
	case strings.HasPrefix(t, "uint256"), strings.HasPrefix(t, "int256"),
		strings.HasPrefix(t, "uint128"), strings.HasPrefix(t, "int128"):
		return "*big.Int"
	case strings.HasPrefix(t, "uint"), strings.HasPrefix(t, "int"):
		return t
	case strings.HasPrefix(t, "bytes"):
		return "[]byte"
	default:
		return "interface{}"
	}
}

func toPascalCase(name string) string {
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	result := strings.Join(parts, "")
	if len(result) > 0 && result[0] >= 'a' && result[0] <= 'z' {
		result = strings.ToUpper(result[:1]) + result[1:]
	}
	return result
}

func renderGoFile(outFile, pkg string, events []GenEvent) error {
	tmplSrc := "// Code generated by chainpulse gen-abi; DO NOT EDIT.\n\n" +
		"package {{.Pkg}}\n\n" +
		"import (\n" +
		`	"math/big"` + "\n\n" +
		`	"github.com/ethereum/go-ethereum/common"` + "\n" +
		")\n\n" +
		"{{range .Events}}" +
		"// {{.Name}} represents the Solidity event.\n" +
		"type {{.Name}} struct {\n" +
		"{{- range .Fields}}" +
		"\t{{.Name}} {{.GoType}} `json:\"{{.JSONTag}}\"`\n" +
		"{{- end}}" +
		"}\n\n" +
		"{{end}}"

	t, err := template.New("abi").Parse(tmplSrc)
	if err != nil {
		return err
	}

	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	defer f.Close()

	type tmplData struct {
		Pkg    string
		Events []GenEvent
	}
	return t.Execute(f, tmplData{Pkg: pkg, Events: events})
}