package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
	"text/template"
)

// Solidity ABI JSON structures (simplified subset)
type abiFile struct {
	ABI []abiEntry `json:"abi"`
}

type abiEntry struct {
	Type      string     `json:"type"`
	Name      string     `json:"name"`
	Inputs    []abiParam `json:"inputs"`
	Anonymous bool       `json:"anonymous,omitempty"`
}

type abiParam struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Indexed bool   `json:"indexed"`
}

type eventDef struct {
	SolName string
	GoName  string
	Fields  []fieldDef
}

type fieldDef struct {
	GoName  string
	GoType  string
	JSONTag string
	Indexed bool
}

var tmpl = `// Code generated by chainpulse gen-abi; DO NOT EDIT.

package {{.Package}}

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

{{range .Events}}
// {{.GoName}} represents the Solidity event {{.SolName}}.
type {{.GoName}} struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.JSONTag}}"` + "`" + `
{{- end}}
}
{{end}}
`

func main() {
	abiPath := flag.String("abi", "", "path to ABI JSON file (e.g., out/EventEmitter.sol/EventEmitter.json)")
	outFile := flag.String("out", "", "output Go file path (e.g., pkg/contracts/eventemitter_gen.go)")
	pkg := flag.String("pkg", "contracts", "Go package name for generated code")
	flag.Parse()

	if *abiPath == "" || *outFile == "" {
		fmt.Fprintf(os.Stderr, "Usage: chainpulse gen-abi -abi <path> -out <path> [-pkg <name>]\n")
		os.Exit(1)
	}

	events, err := parseABI(*abiPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to parse ABI: %v\n", err)
		os.Exit(1)
	}

	if err := generate(*outFile, *pkg, events); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to generate: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %d event structs → %s\n", len(events), *outFile)
}

func parseABI(path string) ([]eventDef, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	var abi abiFile
	if err := json.Unmarshal(data, &abi); err != nil {
		return nil, fmt.Errorf("parse JSON: %w", err)
	}

	var events []eventDef
	for _, entry := range abi.ABI {
		if entry.Type != "event" {
			continue
		}
		ev := eventDef{
			SolName: entry.Name,
			GoName:  toGoName(entry.Name),
		}
		for _, input := range entry.Inputs {
			fd := fieldDef{
				GoName:  toGoName(input.Name),
				GoType:  solTypeToGo(input.Type),
				JSONTag: input.Name,
				Indexed: input.Indexed,
			}
			if input.Indexed {
				fd.JSONTag += ",indexed"
			}
			ev.Fields = append(ev.Fields, fd)
		}
		events = append(events, ev)
	}
	return events, nil
}

func generate(path, pkgName string, events []eventDef) error {
	t, err := template.New("abi").Parse(tmpl)
	if err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	defer f.Close()

	data := struct {
		Package string
		Events  []eventDef
	}{Package: pkgName, Events: events}

	if err := t.Execute(f, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}
	return nil
}

// solTypeToGo maps Solidity types to Go types.
func solTypeToGo(solType string) string {
	switch {
	case solType == "address":
		return "common.Address"
	case solType == "bytes32":
		return "[32]byte"
	case solType == "string":
		return "string"
	case solType == "bool":
		return "bool"
	case strings.HasPrefix(solType, "uint") || strings.HasPrefix(solType, "int"):
		bits := solType[3:]
		if bits == "" || bits == "256" || bits == "128" {
			return "*big.Int"
		}
		if bits == "8" || bits == "16" || bits == "32" || bits == "64" {
			return solType
		}
		return "*big.Int"
	case strings.HasPrefix(solType, "bytes"):
		return "[]byte"
	default:
		return "interface{}"
	}
}

// toGoName converts a snake_case or camelCase name to Go's PascalCase.
func toGoName(name string) string {
	// Handle underscore-separated names
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	result := strings.Join(parts, "")

	// Ensure first char is uppercase for exported types
	if len(result) > 0 && result[0] >= 'a' && result[0] <= 'z' {
		result = strings.ToUpper(result[:1]) + result[1:]
	}
	return result
}
