// Code generated by MockGen. DO NOT EDIT.
// Source: chainpulse/pkg/services/query (interfaces: EventStore,EventMetadataStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_event_store.go -package=query . EventStore,EventMetadataStore
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	core "github.com/rtcdance/chainpulse/pkg/core"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventStore) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventStoreMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventStore)(nil).Close), ctx)
}

// CountEvents mocks base method.
func (m *MockEventStore) CountEvents(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEvents", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEvents indicates an expected call of CountEvents.
func (mr *MockEventStoreMockRecorder) CountEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEvents", reflect.TypeOf((*MockEventStore)(nil).CountEvents), ctx)
}

// DeleteExpiredEvents mocks base method.
func (m *MockEventStore) DeleteExpiredEvents(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredEvents", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredEvents indicates an expected call of DeleteExpiredEvents.
func (mr *MockEventStoreMockRecorder) DeleteExpiredEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredEvents", reflect.TypeOf((*MockEventStore)(nil).DeleteExpiredEvents), ctx)
}

// GetEvent mocks base method.
func (m *MockEventStore) GetEvent(ctx context.Context, eventID string) (*core.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, eventID)
	ret0, _ := ret[0].(*core.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockEventStoreMockRecorder) GetEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockEventStore)(nil).GetEvent), ctx, eventID)
}

// GetEventsByAddress mocks base method.
func (m *MockEventStore) GetEventsByAddress(ctx context.Context, address string, limit int) ([]*core.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByAddress", ctx, address, limit)
	ret0, _ := ret[0].([]*core.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByAddress indicates an expected call of GetEventsByAddress.
func (mr *MockEventStoreMockRecorder) GetEventsByAddress(ctx, address, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByAddress", reflect.TypeOf((*MockEventStore)(nil).GetEventsByAddress), ctx, address, limit)
}

// GetEventsByBlock mocks base method.
func (m *MockEventStore) GetEventsByBlock(ctx context.Context, blockNumber int64) ([]*core.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByBlock", ctx, blockNumber)
	ret0, _ := ret[0].([]*core.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByBlock indicates an expected call of GetEventsByBlock.
func (mr *MockEventStoreMockRecorder) GetEventsByBlock(ctx, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByBlock", reflect.TypeOf((*MockEventStore)(nil).GetEventsByBlock), ctx, blockNumber)
}

// GetEventsByChain mocks base method.
func (m *MockEventStore) GetEventsByChain(ctx context.Context, chainID, limit, offset int) ([]*core.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByChain", ctx, chainID, limit, offset)
	ret0, _ := ret[0].([]*core.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByChain indicates an expected call of GetEventsByChain.
func (mr *MockEventStoreMockRecorder) GetEventsByChain(ctx, chainID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByChain", reflect.TypeOf((*MockEventStore)(nil).GetEventsByChain), ctx, chainID, limit, offset)
}

// GetEventsByContract mocks base method.
func (m *MockEventStore) GetEventsByContract(ctx context.Context, contractAddress string, limit, offset int) ([]*core.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByContract", ctx, contractAddress, limit, offset)
	ret0, _ := ret[0].([]*core.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByContract indicates an expected call of GetEventsByContract.
func (mr *MockEventStoreMockRecorder) GetEventsByContract(ctx, contractAddress, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByContract", reflect.TypeOf((*MockEventStore)(nil).GetEventsByContract), ctx, contractAddress, limit, offset)
}

// GetEventsByEventName mocks base method.
func (m *MockEventStore) GetEventsByEventName(ctx context.Context, eventName string, limit, offset int) ([]*core.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByEventName", ctx, eventName, limit, offset)
	ret0, _ := ret[0].([]*core.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByEventName indicates an expected call of GetEventsByEventName.
func (mr *MockEventStoreMockRecorder) GetEventsByEventName(ctx, eventName, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByEventName", reflect.TypeOf((*MockEventStore)(nil).GetEventsByEventName), ctx, eventName, limit, offset)
}

// GetEventsByName mocks base method.
func (m *MockEventStore) GetEventsByName(ctx context.Context, eventName string, limit int) ([]*core.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByName", ctx, eventName, limit)
	ret0, _ := ret[0].([]*core.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByName indicates an expected call of GetEventsByName.
func (mr *MockEventStoreMockRecorder) GetEventsByName(ctx, eventName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByName", reflect.TypeOf((*MockEventStore)(nil).GetEventsByName), ctx, eventName, limit)
}

// GetEventsByCorrelationID mocks base method.
func (m *MockEventStore) GetEventsByCorrelationID(ctx context.Context, correlationID string, limit, offset int) ([]*core.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByCorrelationID", ctx, correlationID, limit, offset)
	ret0, _ := ret[0].([]*core.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByCorrelationID indicates an expected call of GetEventsByCorrelationID.
func (mr *MockEventStoreMockRecorder) GetEventsByCorrelationID(ctx, correlationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByCorrelationID", reflect.TypeOf((*MockEventStore)(nil).GetEventsByCorrelationID), ctx, correlationID, limit, offset)
}

// GetEventsPaginated mocks base method.
func (m *MockEventStore) GetEventsPaginated(ctx context.Context, cursor string, limit int) ([]*core.BlockchainEvent, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsPaginated", ctx, cursor, limit)
	ret0, _ := ret[0].([]*core.BlockchainEvent)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEventsPaginated indicates an expected call of GetEventsPaginated.
func (mr *MockEventStoreMockRecorder) GetEventsPaginated(ctx, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsPaginated", reflect.TypeOf((*MockEventStore)(nil).GetEventsPaginated), ctx, cursor, limit)
}

// Health mocks base method.
func (m *MockEventStore) Health(ctx context.Context) *core.HealthStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(*core.HealthStatus)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockEventStoreMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockEventStore)(nil).Health), ctx)
}

// Initialize mocks base method.
func (m *MockEventStore) Initialize(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockEventStoreMockRecorder) Initialize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockEventStore)(nil).Initialize), ctx)
}

// InsertEvent mocks base method.
func (m *MockEventStore) InsertEvent(ctx context.Context, event *core.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockEventStoreMockRecorder) InsertEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockEventStore)(nil).InsertEvent), ctx, event)
}

// InsertEventBatch mocks base method.
func (m *MockEventStore) InsertEventBatch(ctx context.Context, events []*core.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEventBatch", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEventBatch indicates an expected call of InsertEventBatch.
func (mr *MockEventStoreMockRecorder) InsertEventBatch(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEventBatch", reflect.TypeOf((*MockEventStore)(nil).InsertEventBatch), ctx, events)
}

// GetEventStats mocks base method.
func (m *MockEventStore) GetEventStats(ctx context.Context) (map[string]int64, map[string]int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventStats", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(map[string]int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetEventStats indicates an expected call of GetEventStats.
func (mr *MockEventStoreMockRecorder) GetEventStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventStats", reflect.TypeOf((*MockEventStore)(nil).GetEventStats), ctx)
}

// MockEventMetadataStore is a mock of EventMetadataStore interface.
type MockEventMetadataStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventMetadataStoreMockRecorder
	isgomock struct{}
}

// MockEventMetadataStoreMockRecorder is the mock recorder for MockEventMetadataStore.
type MockEventMetadataStoreMockRecorder struct {
	mock *MockEventMetadataStore
}

// NewMockEventMetadataStore creates a new mock instance.
func NewMockEventMetadataStore(ctrl *gomock.Controller) *MockEventMetadataStore {
	mock := &MockEventMetadataStore{ctrl: ctrl}
	mock.recorder = &MockEventMetadataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventMetadataStore) EXPECT() *MockEventMetadataStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventMetadataStore) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventMetadataStoreMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventMetadataStore)(nil).Close), ctx)
}

// GetMetadata mocks base method.
func (m *MockEventMetadataStore) GetMetadata(ctx context.Context, eventID string) (*EventMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, eventID)
	ret0, _ := ret[0].(*EventMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockEventMetadataStoreMockRecorder) GetMetadata(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockEventMetadataStore)(nil).GetMetadata), ctx, eventID)
}

// GetMetadataByChain mocks base method.
func (m *MockEventMetadataStore) GetMetadataByChain(ctx context.Context, chainID, limit, offset int) ([]*EventMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataByChain", ctx, chainID, limit, offset)
	ret0, _ := ret[0].([]*EventMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataByChain indicates an expected call of GetMetadataByChain.
func (mr *MockEventMetadataStoreMockRecorder) GetMetadataByChain(ctx, chainID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataByChain", reflect.TypeOf((*MockEventMetadataStore)(nil).GetMetadataByChain), ctx, chainID, limit, offset)
}

// GetMetadataBatch mocks base method.
func (m *MockEventMetadataStore) GetMetadataBatch(ctx context.Context, eventIDs []string) (map[string]*EventMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataBatch", ctx, eventIDs)
	ret0, _ := ret[0].(map[string]*EventMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataBatch indicates an expected call of GetMetadataBatch.
func (mr *MockEventMetadataStoreMockRecorder) GetMetadataBatch(ctx, eventIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataBatch", reflect.TypeOf((*MockEventMetadataStore)(nil).GetMetadataBatch), ctx, eventIDs)
}

// Health mocks base method.
func (m *MockEventMetadataStore) Health(ctx context.Context) *core.HealthStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(*core.HealthStatus)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockEventMetadataStoreMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockEventMetadataStore)(nil).Health), ctx)
}

// Initialize mocks base method.
func (m *MockEventMetadataStore) Initialize(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockEventMetadataStoreMockRecorder) Initialize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockEventMetadataStore)(nil).Initialize), ctx)
}

// InsertMetadata mocks base method.
func (m *MockEventMetadataStore) InsertMetadata(ctx context.Context, metadata *EventMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMetadata", ctx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMetadata indicates an expected call of InsertMetadata.
func (mr *MockEventMetadataStoreMockRecorder) InsertMetadata(ctx, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMetadata", reflect.TypeOf((*MockEventMetadataStore)(nil).InsertMetadata), ctx, metadata)
}

// InsertMetadataBatch mocks base method.
func (m *MockEventMetadataStore) InsertMetadataBatch(ctx context.Context, metadataList []*EventMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMetadataBatch", ctx, metadataList)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMetadataBatch indicates an expected call of InsertMetadataBatch.
func (mr *MockEventMetadataStoreMockRecorder) InsertMetadataBatch(ctx, metadataList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMetadataBatch", reflect.TypeOf((*MockEventMetadataStore)(nil).InsertMetadataBatch), ctx, metadataList)
}

// UpdateMetadata mocks base method.
func (m *MockEventMetadataStore) UpdateMetadata(ctx context.Context, metadata *EventMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", ctx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockEventMetadataStoreMockRecorder) UpdateMetadata(ctx, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockEventMetadataStore)(nil).UpdateMetadata), ctx, metadata)
}
