apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: chainpulse
data:
  kafka_server_jaas.conf: |
    KafkaServer {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="admin"
      password="admin"
      user_admin="admin";
    };
    Client {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="admin"
      password="admin";
    };
  kafka-client.properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
