apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainpulse
  namespace: chainpulse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainpulse-monolithic
  namespace: chainpulse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainpulse-puller
  namespace: chainpulse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainpulse-event-processor
  namespace: chainpulse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainpulse-api-service
  namespace: chainpulse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainpulse-api-gateway
  namespace: chainpulse