// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"

	"github.com/rtcdance/chainpulse/pkg/core"
)

// InitializeMonolithicRuntime creates the monolithic runtime wiring using
// dependency injection. This file is generated by Wire from wire.go.
// To regenerate: go generate ./pkg/application/bootstrap/
func InitializeMonolithicRuntime(
	ctx context.Context,
	cfg core.Config,
	logLevel string,
) (*RuntimeWiring, error) {
	return BuildRuntimeWiring(ctx, provideLogger(), provideMetrics())
}

func provideLogger() core.Logger {
	return core.NewSlogLogger(core.LogLevelInfo, "slog")
}

func provideMetrics() core.MetricsCollector {
	return core.NewDefaultMetricsCollector()
}

var _ = context.Background
